### PR TITLE
adding a few little things

### PR DESCRIPTION
**Pull request by bltzr**
- a proposed `none` UNIT (this came in handy when trying to implement the EXTENDED_TYPEs in libossia)
- an extra `time.samples` UNIT
- notes about mutual-convertibility of UNITs of the same category

### CODE REVIEW

**Comment by jcelerier** [comment]
> a proposed none UNIT (this came in handy when trying to implement the EXTENDED_TYPEs in libossia)

... uh ?

**Comment by bltzr** [comment]
don't worry @jcelerier, that's just an experiment on a fork (for colors, where there is no unit, but that's probably not done in a nice way, though) - plus you're supposed to be on vacation ;-p

**Comment by bltzr** [comment]
anyway, I was just asking if this would make sense, generally - of course I'm not asking that we change the specs to fit my murky experiments

**Comment by mrRay** [comment]
between the fact that i didn't agree with everything 100% and wanted to change some stuff, and there were multiple pull requests with a variety of different changes, and the other changes i was working on that in some cases were related, i thought it simplest to consolidate everything into the commit i just pushed (87144872d1c34bb1005a7e5a4606b412be971242).  please open a new PR if you feel i missed, overlooked, or dropped anything inappropriately!

**Comment by bltzr** [comment]
No problem, @mrRay, as always, you did a great job at taking the best of my proposals and making them better, while leaving the dubious parts aside, so, thanks again for that!

re-reading the whole document (README) here come a few notes and (sometimes minor) remarks:
- null is obviously the right way to dal with the "none" case I was mentioning
- in the beginning, you write: "I've also put together a Cocoa framework ". Since this repo is not owned anymore by you, but by vidvox, it's not really clear who's "I" -> replacing this by @mrRay, VidVox or just "we" could help
- you mention @jcelerier 's coppa initial implementation. I'm wondering if there's still any point to mention it at all, of if we could just mention libossia, something like: "@jcelerier started work on the first implementation of this protocol, that has been since been merged into the ossia library." (we could leave an hyperlink on "first implementation" if we want to make 22nd century's media-art historians' work easier ;-p
- for CLIPMODEs, we're also using "wrap" and "fold" clipmodes in ossia, which might interesting to include (I'll leave the decision to you on this)
- I also have a few comments on the UI part, but I'll do that on the dedicated issue

**Comment by bltzr** [comment]
also, in the EXTENDED_TYPE section, you included the phrasing I proposed:  "currently being assembled here" - but is that still relevant, or shouldn't it rather be changed to something more assertive like "available here" ?

**Pull request closed without merging**
