### PR TITLE
extended documentation on EXTENDED_TYPE

### PR DESCRIPTION
**Pull request by bltzr**
as discussed in https://github.com/Vidvox/OSCQueryProposal/issues/38 here is a proposal of further documentation on EXTENDED_TYPE (and their disambiguation/split with UNITs)

### CODE REVIEW

**Comment by mrRay** [comment]
thanks for this, it's very helpful!

- i'm not sure i understand your use of the EXTENDED_TYPE 'list'.  i think i'm confused because we have to provide one EXTENDED_TYPE per value- so where/how would this be used?  wouldn't you be forced to apply the EXTENDED_TYPE 'list' to every member of the list?  i have the same basic question about 'stringArray', 'floatArray', and 'integerArray'.

- i don't think an EXTENDED_TYPE for 'bool' is appropriate?  this attribute is supposed to provide additional semantic information about a value: 'bool' does not describe what the value is or what it does, i don't think?  it's close, but i don't think it's quite the same thing.

- is it okay with you if i re-word some stuff without changing the meaning?

**Comment by bltzr** [comment]
hi!

I'm glad that helps.

> i'm not sure i understand your use of the EXTENDED_TYPE 'list'. i think i'm confused because we have to provide one EXTENDED_TYPE per value- so where/how would this be used? wouldn't you be forced to apply the EXTENDED_TYPE 'list' to every member of the list? i have the same basic question about 'stringArray', 'floatArray', and 'integerArray'.

yes, you're right, I guess.
since you added the no-array rule lately, this would actually be applied to every value, and that would show that each of them is a member of a list or *Array. But maybe that's sloppy design, and if you think that is, then please feel free to remove that altogether.

> i don't think an EXTENDED_TYPE for 'bool' is appropriate? this attribute is supposed to provide additional semantic information about a value: 'bool' does not describe what the value is or what it does, i don't think? it's close, but i don't think it's quite the same thing.

Well, that was an experiment, actually. I was thinking that might help on the int[0-1]/T-F issue, but that seems to be settled now, so, yeah, this can go away.

> is it okay with you if i re-word some stuff without changing the meaning?

of course! :-)

**Comment by bltzr** [comment]
actually, for "list" and "*Array", I just put in what @jcelerier had put into the libossia implementation, but we're in the process of changing this (or at least the way it is "translated" into OSCQuery), so don't worry too much about it

**Comment by mrRay** [comment]
i wound up changing a couple more things.  specifically:

- added a note that it is not necessary to make use of all components- for example, 'color.rgb.[rgba]' is a type- but if you only want an RGB color, you can simply not make use of 'color.rgb.a'.
- i changed some of the notation for the spherical and cylindrical notation types to correspond with what i think is more conventional?  i wasn't sure what "aed" was supposed to mean and the ISO docs listed the notation differently...
- i got rid of position.openGL entirely for various reasons (redundant with position.cart3D.xyz, my understanding is that values depend largely on the transform matrices in use at any given time, which are decidedly non-standard)
- i got rid of color.rgb8 and color.cmy8 because they seemed unnecessary/redundant (i added color.cmyk)
- i added optional alpha channels for the various color spaces- ex: color.hsv.[hsva], color.ciexyz.[xyza], etc.

...this is probably getting confusing, and i don't think i made any changes that you'd object to so i'm just going to commit at this point.  if i messed anything up or you'd like to see any of the changes i made un-done, please open an issue- and thanks again for submitting this!

**Comment by bltzr** [comment]
I was also wondering if we couldn't apply the same principle of an optional dimension to position - which could do something like this:
```
position.cartesian.[xy(z)]- A point in space, consisting of x, y, and (optional) z components.

x- A number value describing a distance.
y- A number value describing a distance.
(z=0.- A number value describing a distance.)
```

of course, I'm still not sure about the way to indicate the optional part (and you're much better than I do at formulating things clearly) , but you get the idea ?

**Comment by bltzr** [comment]
that's more difficult to achieve with polar and spherical, since the optional one is in the middle, but maybe that can stay the way it is ?

BTW, I used  the naming conventions you mentioned ("aed“, and so on) because those were used in Jamoma, and I thought they were usual in the domain of spatial sound, AFAIK, but you're right that using ISO is better.

**Comment by bltzr** [comment]
for reference, here's one place where things are presented this way, and the OpenGL/"standard" conversion is also discussed - p.13 of 
http://redmine.spatdif.org/attachments/download/105/SpatDIF-specs-V0.3.pdf

**Comment by mrRay** [comment]
> I find the optional alpha to be a great idea, but maybe that could be made more explicit, maybe with something like this:
> color.rgb.[rgb(a)]- A color value described in the RGB space, potentially including an alpha channel.

this implies that only the alpha is optional- all of the components are optional!  for example, the following OSC methods are perfectly valid:

~~~json
"RED": {
	"FULL_PATH": "/image/red",
	"TYPE": "f",
	"EXTENDED_TYPE": [ "color.rgb.r" ]
},
"ALPHA": {
	"FULL_PATH": "/image/alpha",
	"TYPE": "f",
	"EXTENDED_TYPE": [ "color.rgb.a" ]
},
~~~

...i did state this explicitly at the top of the doc, but i guess i didn't do a good enough job of clarifying what i meant!  is the following a little bit clearer?

> Not all of these attributes are required to be used- for example, `color.rgb.[rgba]` potentially includes `color.rgb.r`, `color.rgb.g`, `color.rgb.b`, and `color.rgb.a`, but you don't need to make use of all of them all the time- it's perfectly fine to have an OSC method that only accepts a single float and has the EXTENDED_TYPE `color.rgb.r`, or any other combination of recognized EXTENDED_TYPE values in any order.


<BR>

> "I'm also dubitative about removing the 8-bit versions (except of course for rgb, which is the standard "r", so no need for extra info)"

- the OSC spec already has a native 8 bits per channel RGBA data type
- why?  what does it provide that `color.rgb.[rgba]` does not?
- you still have to explicitly specify a MIN and a MAX, so i don't think it saves us anything?  we can't assume ranges based on EXTENDED_TYPE- this practice cannot be applied consistently to other extended types in a variety of situations.
- does this situation correspond to any of the situation in which it is appropriate or necessary to describe the bitdepth of a color channel?


> "I was also wondering if we couldn't apply the same principle of an optional dimension to position - which could do something like this:"

oh yeah, that's a great point- i'll get rid of the 2D/3D distinction for cartesian coords.  good catch!


> "that's more difficult to achieve with polar and spherical, since the optional one is in the middle, but maybe that can stay the way it is ?"

- hmm, doesn't polar map to both spherical and cylindrical?  i think that'd be a problem too- it may be possible, but i think it'd probably be messy- perhaps it's best if we keep these separate...
- there is no "middle" because the order doesn't matter, and they're all optional!

**Comment by bltzr** [comment]
> ...i did state this explicitly at the top of the doc, but i guess i didn't do a good enough job of clarifying what i meant!

that might because you showed that with just the alpha, which is stated as optional...
anyway, the new phrasing is much much clearer, thanks !

I also have a few other thoughts:
- why `position.cart` and not `position.cartesian` when no other abbreviation is used ?
- I find the positioning of the "accessor" (x, y, z, etc...) just before the URL types a little confusing
- the examples take a lot of estate

So, I have tried to move all of this and created another pull request, tell me what you think.

**Comment by bltzr** [comment]
BTW, just re-read your comment, and I found this phrasing quite clear,
> you don't need to make use of all of them all the time- it's perfectly fine to have an OSC method that only accepts a single float and has the EXTENDED_TYPE color.rgb.r, or any other combination of recognized EXTENDED_TYPE values in any order.

maybe it could reintroduced ?

Also, to reply to the other points:

- yes, you're probably right that we don't need 8-bit versions: they can be expressed with the RANGE attribute, and also potentially by TYPEs. So, yeah, let's KISS

- concerning the various polar position flavors, I have made a little experiment here:
https://github.com/OSSIA/OSCQueryProposal/blob/polar-merge/extended_types.md
I'm not 100% sure it is better this way... 

I've been even thinking of pushing things even a little further: since all "accessors" (that's how we call the char at the end describing x, y, a, etc...) are unique inside of a "category" (well, except, the y's for the yaw, and for the CIE Y (which is usually uppercase), so I've tried uppercasing them), do we really need to express the coordinate type (i.e. rgb or polar) ? I have made a little experiment here:
https://github.com/OSSIA/OSCQueryProposal/blob/global-merge/extended_types.md
but that's probably stretching it too far... what do you think ?

**Pull request closed without merging**
